### ISSUE TITLE
항해 Lv2 과제 코드리뷰

### ISSUE THREAD

**Issue by ByHorizon** [SeoYoonP/HanghaeAssignment01#5]
PostController에 글 삭제 ,성공 시 메시지와 상태코드를 함께 보내주어야 하는데 메시지만 보내주신 것으로 보여집니다!! UserControler에는 잘 쓰신 것으로 보아 아마 깜빡하신게 아닐까 하고 남겨드립니다! 너무너무 고생많으셨습니다

**Comment by SeoYoonP** [comment]
엇 빼먹은게 있었네요 리뷰 너무감사드립니다!
